apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-backend-deployment
  labels:
    app: php-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-backend-deployment
  template:
    metadata:
      labels:
        app: php-backend-deployment
    spec:
      containers:
      - name: php-backend-deployment
        image: shockley09/php-backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
